title: Sun Lab
email: sunw37@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sun Lab @ Cornell
baseurl: "/my-awesome-site" # the subpath of your site, e.g. /blog
url: "https://neuroai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sunw37
github_username: neuroai

# Build settings
theme: minima
plugins:
  - jekyll-feed
